import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { motion, AnimatePresence } from 'framer-motion';
import { Briefcase, GraduationCap, Code2, Languages, MapPin, Calendar, Award, ChevronRight, Download, Mail, Globe2, Search, Sparkles, UserRound, Menu, X, Guitar, Plane, Dumbbell, Building2 } from 'lucide-react';
import './styles.css';

const data = {
  de: {
    nav: { profile: 'Profil', experience: 'Werdegang', education: 'Studium', skills: 'Kenntnisse', contact: 'Kontakt' },
    hero: {
      name: 'Marcel Wlotzka', degree: 'M.Sc. Informatik', role: 'Sachgebietsleiter IT Strategie und Architektur', location: 'Lautertal, Deutschland', born: 'Geboren am 9. August 1989 in Goch', maritalStatus: 'Verheiratet, 2 Kinder', email: 'marcel@wlotzka.org',
      tagline: 'IT-Strategie, Architektur und Innovation mit Praxisnähe: von Smart-City-Plattformen über KI und Automatisierung bis zu skalierbaren digitalen Lösungen.',
      highlights: ['Disziplinarische und fachliche Führung', 'IT-Strategie & Architektur', 'SmartCity-Plattform ausgezeichnet mit VKU Innovationspreis 2023', 'Softwareentwicklung, App-Entwicklung & Cloud-nahe Architekturen']
    },
    stats: [{ label: 'Jahre IT-Erfahrung', value: '18+' }, { label: 'Mainova Stationen', value: '4' }, { label: 'Abschluss', value: 'M.Sc.' }, { label: 'Technologiefelder', value: 'KI · VR · SmartCity' }],
    sections: { profileEyebrow: 'Kurzprofil', profileTitle: 'Profil', profileText: 'Ich verbinde technologische Tiefe mit strategischer Perspektive. Mein Schwerpunkt liegt darauf, neue Technologien für den Unternehmenskontext nutzbar zu machen, Architekturentscheidungen tragfähig zu gestalten und Teams bei der Umsetzung digitaler Lösungen zu befähigen.', experienceEyebrow: 'Werdegang', experienceTitle: 'Beruflicher Werdegang', educationEyebrow: 'Ausbildung', educationTitle: 'Schule & Studium', skillsEyebrow: 'Technologien', skillsTitle: 'Kenntnisse & Technologien', languagesTitle: 'Sprachen', hobbiesTitle: 'Hobbies', searchPlaceholder: 'Stationen, Technologien oder Themen suchen …', contactEyebrow: 'Kontakt', contactTitle: 'Kontakt & Downloads', contactText: 'Gerne per E-Mail oder LinkedIn kontaktieren. Den Lebenslauf gibt es passend zur ausgewählten Sprache als PDF.' },
    filters: { all: 'Alle', leadership: 'Führung', architecture: 'Architektur', development: 'Entwicklung', innovation: 'Innovation' },
    pdf: { de: 'Lebenslauf herunterladen', en: 'Download CV' },
    experience: [
      { period: '01/2026 – Heute', company: 'Mainova AG', role: 'Sachgebietsleiter IT Strategie und Architektur', tags: ['leadership','architecture'], bullets: ['Disziplinarische und fachliche Führung', 'KI-Beauftragter'] },
      { period: '10/2024 – 12/2025', company: 'Mainova AG', role: 'IT Architekt', tags: ['architecture'], bullets: ['Mainova IT'] },
      { period: '09/2020 – 10/2024', company: 'Mainova AG', role: 'SmartCity Solution Architekt', tags: ['architecture','innovation','development'], bullets: ['Entwicklung der SmartCity Plattform der Mainova', 'Ausgezeichnet mit dem VKU Innovationspreis 2023'], badge: 'VKU Innovationspreis 2023' },
      { period: '09/2018 – 09/2020', company: 'Mainova AG', role: 'IT Innovation Manager', tags: ['innovation'], bullets: ['Evaluation neuer Technologien in der Energiewirtschaft', 'Schulung von Mitarbeitenden zu neuen Technologiefeldern', 'Projekte in KI, VR, SmartCity, Blockchain sowie Prozessoptimierung und Automatisierung'] },
      { period: '09/2016 – 09/2018', company: 'CMF Advertising GmbH', role: 'Leiter der Softwareentwicklung', tags: ['leadership','development'], bullets: ['Eigenverantwortliche Entwicklung von Web- und App-Projekten auf Kundenwunsch', 'Koordination des Teams mit anderen Abteilungen'] },
      { period: '08/2014 – 08/2016', company: '2VizCon GmbH, Neu-Isenburg', role: 'App Developer', tags: ['development'], bullets: ['Entwicklung von Apps für iOS, Android, Windows und Windows Phone', 'Weiterentwicklung eines App-Containers zur Darstellung webbasierter Inhalte', 'Entwicklung automatischer Build-Prozesse für Apps', 'Beratung der Geschäftsführung und Kunden in App-Fragen'] },
      { period: '08/2009 – 08/2014', company: 'KWP GmbH & Co. KG, Neu-Isenburg', role: 'Werkstudent Web Developer', tags: ['development'], bullets: ['Werkstudent, zwei Tage pro Woche als Web Developer', 'Eigenständige Weiterbildung zum App Developer', 'Verantwortung für viele IT-relevante Anliegen'] },
      { period: '09/2008 – 06/2009', company: 'XYQOM GmbH, Waldbröl bei Köln', role: 'Schulische Aushilfe Template & Webentwicklung', tags: ['development'], bullets: ['Template-Umsetzung in TypoLight / Contao für Kundenwebseiten', 'Erstellung kleinerer TypoLight-Erweiterungen', 'HTML5-Bestellsystem mit Konfigurator für KRONE-Sattelauflieger'] },
      { period: '07/2007 – 09/2009', company: 'Da Source Distribution, Köln', role: 'Schulische Aushilfe Online-Shop', tags: ['development'], bullets: ['Pflege eines ASP.NET-basierten Online-Shops für DJ-Equipment und Schallplatten', 'API-Anbindung zur Synchronisation von Produktinformationen und Mengenangaben mit eBay und internationalen Online-Shops'] }
    ],
    education: [
      { period: '04/2013 – 08/2018', institution: 'Technische Universität Darmstadt', title: 'Master of Science Informatik mit Anwendungsfach IT-Management', grade: 'Durchschnitt: 1,87', details: ['Schwerpunkte: Data and Knowledge Engineering, Human Computer Systems, Net Centric Systems, Software Engineering', 'Master Thesis: Kontextsensitives Nachschlagen von lexikalisch-semantischen und syntaktischen Angaben in Schreibassistenzsystemen, verfasst in Englisch'] },
      { period: '10/2009 – 04/2013', institution: 'Technische Universität Darmstadt', title: 'Bachelor of Science Informatik', grade: 'Durchschnitt: 2,5', details: ['Bachelor Thesis: Delay-tolerante Datenübertragung in mobilen Sensornetzen, verfasst in Deutsch'] },
      { period: '1996 – 2009', institution: 'Willibrord Gymnasium Emmerich, NRW', title: 'Abitur', grade: 'Durchschnitt: 2,3', details: ['Abiturfächer: Mathe LK, Geschichte LK, Englisch, Informatik'] }
    ],
    skills: [{ group: 'Programmiersprachen', icon: Code2, items: ['Objective-C','Swift','C / C++','C#','Java','JavaScript','TypeScript','PHP','ASP.NET'] }, { group: 'Systeme & Frameworks', icon: Building2, items: ['Linux-Serveradministration','Windows-Serveradministration','Polymer','ReactJS','Vue.js','Symfony','Laravel','Node.js','Chromium Embedded Framework'] }],
    spokenLanguages: ['Deutsch', 'Englisch in Wort und Schrift'], hobbies: [{ label: 'Badminton', icon: Dumbbell }, { label: 'Drohne fliegen', icon: Plane }, { label: 'Gitarre spielen', icon: Guitar }]
  },
};

data.en = {
  ...data.de,
  nav: { profile: 'Profile', experience: 'Experience', education: 'Education', skills: 'Skills', contact: 'Contact' },
  hero: { ...data.de.hero, degree: 'M.Sc. Computer Science', role: 'Head of IT Strategy and Architecture Team', location: 'Lautertal, Germany', born: 'Born on August 9, 1989 in Goch, Germany', maritalStatus: 'Married, 2 children', tagline: 'IT strategy, architecture and innovation with hands-on depth: from smart-city platforms to AI, automation and scalable digital solutions.', highlights: ['Disciplinary and functional leadership', 'IT strategy & architecture', 'SmartCity platform awarded with the VKU Innovation Award 2023', 'Software development, app development and cloud-adjacent architectures'] },
  stats: [{ label: 'Years of IT experience', value: '18+' }, { label: 'Mainova roles', value: '4' }, { label: 'Degree', value: 'M.Sc.' }, { label: 'Technology fields', value: 'AI · VR · SmartCity' }],
  sections: { profileEyebrow: 'Profile', profileTitle: 'Profile', profileText: 'I combine technical depth with a strategic perspective. My focus is on making emerging technologies usable in an enterprise context, shaping sustainable architecture decisions and enabling teams to implement digital solutions.', experienceEyebrow: 'Career', experienceTitle: 'Professional Experience', educationEyebrow: 'Education', educationTitle: 'Education', skillsEyebrow: 'Technologies', skillsTitle: 'Skills & Technologies', languagesTitle: 'Languages', hobbiesTitle: 'Hobbies', searchPlaceholder: 'Search roles, technologies or topics …', contactEyebrow: 'Contact', contactTitle: 'Contact & Downloads', contactText: 'Feel free to get in touch by email or LinkedIn. The CV is available as a PDF matching the selected language.' },
  filters: { all: 'All', leadership: 'Leadership', architecture: 'Architecture', development: 'Development', innovation: 'Innovation' },
  pdf: { de: 'Lebenslauf herunterladen', en: 'Download CV' },
  experience: data.de.experience.map(x => ({ ...x })).map((x, i) => Object.assign(x, [
    { period:'01/2026 – Present', role:'Head of IT Strategy and Architecture Team', bullets:['Disciplinary and functional leadership', 'AI Officer'] },
    { period:'10/2024 – 12/2025', role:'IT Architect', bullets:['Mainova IT'] },
    { period:'09/2020 – 10/2024', role:'SmartCity Solution Architect', bullets:["Development of Mainova's SmartCity platform", 'Awarded with the VKU Innovation Award 2023'], badge:'VKU Innovation Award 2023' },
    { period:'09/2018 – 09/2020', role:'IT Innovation Manager', bullets:['Evaluation of emerging technologies in the energy sector', 'Training employees in new technology areas', 'Projects in AI, VR, SmartCity, blockchain and internal process optimization / automation'] },
    { period:'09/2016 – 09/2018', role:'Head of Software Development', bullets:['Independent development of customer-specific web and app projects', 'Coordination of the team with other departments'] },
    { period:'08/2014 – 08/2016', role:'App Developer', bullets:['Development of apps for iOS, Android, Windows and Windows Phone', 'Further development of an app container for displaying web-based content', 'Development of automated build processes for apps', 'Advising management and customers on app-related questions'] },
    { period:'08/2009 – 08/2014', role:'Working Student Web Developer', bullets:['Working student, two days per week as web developer', 'Self-directed development into app development', 'Responsible for many IT-related topics'] },
    { period:'09/2008 – 06/2009', role:'Student Assistant Template & Web Development', company:'XYQOM GmbH, Waldbröl near Cologne', bullets:['Template implementation in TypoLight / Contao for customer websites', 'Creation of smaller TypoLight extensions', 'HTML5 ordering system with configurator for KRONE semi-trailers'] },
    { period:'07/2007 – 09/2009', role:'Student Assistant Online Shop', company:'Da Source Distribution, Cologne', bullets:['Maintenance of an ASP.NET-based online shop for DJ equipment and vinyl records', 'API integration for synchronizing product information and quantities with eBay and international online shops'] }
  ][i])),
  education: [
    { period:'04/2013 – 08/2018', institution:'Technical University of Darmstadt', title:'Master of Science Computer Science with minor in IT Management', grade:'Grade average: 1.87', details:['Focus areas: Data and Knowledge Engineering, Human Computer Systems, Net Centric Systems, Software Engineering', 'Master thesis: Context-sensitive lookup of lexical-semantic and syntactic information in writing assistance systems, written in English'] },
    { period:'10/2009 – 04/2013', institution:'Technical University of Darmstadt', title:'Bachelor of Science Computer Science', grade:'Grade average: 2.5', details:['Bachelor thesis: Delay-tolerant data transmission in mobile sensor networks, written in German'] },
    { period:'1996 – 2009', institution:'Willibrord Gymnasium Emmerich, NRW', title:'Abitur / German university entrance qualification', grade:'Grade average: 2.3', details:['Exam subjects: Mathematics advanced course, History advanced course, English, Computer Science'] }
  ],
  skills: [{ group: 'Programming Languages', icon: Code2, items: data.de.skills[0].items }, { group: 'Systems & Frameworks', icon: Building2, items: ['Linux server administration','Windows server administration','Polymer','ReactJS','Vue.js','Symfony','Laravel','Node.js','Chromium Embedded Framework'] }],
  spokenLanguages: ['German', 'English spoken and written'], hobbies: [{ label: 'Badminton', icon: Dumbbell }, { label: 'Flying drones', icon: Plane }, { label: 'Playing guitar', icon: Guitar }]
};

const cls = (...v) => v.filter(Boolean).join(' ');
const publicAsset = (file) => `${import.meta.env.BASE_URL}${file}`;
const getInitialLang = () => {
  if (typeof navigator === 'undefined') return 'de';
  const languages = navigator.languages?.length ? navigator.languages : [navigator.language];
  const [primaryLanguage = ''] = languages;
  return primaryLanguage.toLowerCase().startsWith('de') ? 'de' : 'en';
};

function Section({ id, eyebrow, title, children }) { return <section id={id} className="section-block"><motion.div initial={{opacity:0,y:18}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin:'-80px'}}><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{children}</motion.div></section> }
function Nav({ t, lang, setLang }) { const [open,setOpen]=useState(false); const links=[['profile',t.nav.profile],['experience',t.nav.experience],['education',t.nav.education],['skills',t.nav.skills],['contact',t.nav.contact]]; return <header className="nav"><div className="nav-inner"><a href="#top" className="brand"><img src={publicAsset('marcel-wlotzka.jpg')}/><span><b>Marcel Wlotzka</b><small>Interactive CV</small></span></a><nav>{links.map(([h,l])=><a key={h} href={'#'+h}>{l}</a>)}</nav><div className="lang"><button onClick={()=>setLang('de')} className={lang==='de'?'active':''}>DE</button><button onClick={()=>setLang('en')} className={lang==='en'?'active':''}>EN</button><button className="mobile" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></div><AnimatePresence>{open&&<motion.div className="mobile-menu" initial={{height:0}} animate={{height:'auto'}} exit={{height:0}}>{links.map(([h,l])=><a onClick={()=>setOpen(false)} key={h} href={'#'+h}>{l}</a>)}</motion.div>}</AnimatePresence></header> }
function Hero({t}) { return <section id="top" className="hero"><div className="hero-grid"><motion.div initial={{opacity:0,y:24}} animate={{opacity:1,y:0}}><span className="pill"><Sparkles size={16}/>{t.hero.degree}</span><h1>{t.hero.name}</h1><h3>{t.hero.role}</h3><p>{t.hero.tagline}</p><div className="actions"><a className="primary" href="#experience">CV ansehen <ChevronRight size={18}/></a><a className="secondary" href={'mailto:'+t.hero.email}><Mail size={18}/> {t.hero.email}</a></div></motion.div><motion.aside className="photo-card" initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}}><img src={publicAsset('marcel-wlotzka.jpg')} alt="Marcel Wlotzka"/><div className="info"><p><MapPin size={16}/>{t.hero.location}</p><p><Calendar size={16}/>{t.hero.born}</p><p><UserRound size={16}/>{t.hero.maritalStatus}</p></div>{t.hero.highlights.map(h=><div className="highlight" key={h}>{h}</div>)}</motion.aside></div><Stats t={t}/></section> }
function Stats({t}) { return <div className="stats">{t.stats.map(s=><div className="stat" key={s.label}><b>{s.value}</b><span>{s.label}</span></div>)}</div> }
function Experience({t}) { const [filter,setFilter]=useState('all'), [q,setQ]=useState(''), [expanded,setExpanded]=useState(0); const filtered=useMemo(()=>t.experience.filter(item=>{const hay=[item.period,item.company,item.role,...item.bullets,...item.tags].join(' ').toLowerCase();return (filter==='all'||item.tags.includes(filter)) && (!q||hay.includes(q.toLowerCase()))}),[t,filter,q]); return <Section id="experience" eyebrow={t.sections.experienceEyebrow} title={t.sections.experienceTitle}><div className="tools"><label><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={t.sections.searchPlaceholder}/></label><div>{Object.entries(t.filters).map(([k,l])=><button className={filter===k?'active':''} onClick={()=>setFilter(k)} key={k}>{l}</button>)}</div></div><div className="timeline">{filtered.map((item,i)=><article key={item.period+item.role}><button onClick={()=>setExpanded(expanded===i?-1:i)}><span className="dot"/><div className="row"><div><small>{item.period}</small><h3>{item.role}</h3><p>{item.company}</p></div><div className="tags">{item.badge&&<em><Award size={14}/>{item.badge}</em>}{item.tags.map(tag=><span key={tag}>{t.filters[tag]}</span>)}</div></div><AnimatePresence>{expanded===i&&<motion.ul initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}}>{item.bullets.map(b=><li key={b}><ChevronRight size={16}/>{b}</li>)}</motion.ul>}</AnimatePresence></button></article>)}</div></Section> }
function Education({t}) { return <Section id="education" eyebrow={t.sections.educationEyebrow} title={t.sections.educationTitle}><div className="cards three">{t.education.map(e=><article className="card" key={e.title}><div className="card-meta"><GraduationCap size={20}/><small>{e.period}</small></div><h3>{e.title}</h3><p>{e.institution}</p><b>{e.grade}</b>{e.details.map(d=><p className="detail" key={d}>{d}</p>)}</article>)}</div></Section> }
function Skills({t}) { return <Section id="skills" eyebrow={t.sections.skillsEyebrow} title={t.sections.skillsTitle}><div className="cards two">{t.skills.map(g=>{const Icon=g.icon; return <article className="card" key={g.group}><Icon/><h3>{g.group}</h3><div className="chips">{g.items.map(i=><span key={i}>{i}</span>)}</div></article>})}</div><div className="cards two lower"><article className="card"><Languages/><h3>{t.sections.languagesTitle}</h3><div className="chips">{t.spokenLanguages.map(l=><span key={l}>{l}</span>)}</div></article><article className="card"><Sparkles/><h3>{t.sections.hobbiesTitle}</h3><div className="hobbies">{t.hobbies.map(h=>{const Icon=h.icon;return <span key={h.label}><Icon size={18}/>{h.label}</span>})}</div></article></div></Section> }
function Contact({t, lang}) { const pdfHref = publicAsset(lang === 'de' ? 'Marcel_Wlotzka_Lebenslauf_DE.pdf' : 'Marcel_Wlotzka_CV_EN.pdf'); return <Section id="contact" eyebrow={t.sections.contactEyebrow} title={t.sections.contactTitle}><div className="contact"><p>{t.sections.contactText}</p><div className="actions"><a className="primary" href={'mailto:'+t.hero.email}><Mail size={18}/> {t.hero.email}</a><a className="secondary" href={pdfHref} target="_blank" rel="noopener noreferrer"><Download size={18}/> {t.pdf[lang]}</a><a className="secondary" href="https://www.linkedin.com/in/marcel-wlotzka-5b61a0a4" target="_blank" rel="noopener noreferrer"><Globe2 size={18}/> LinkedIn</a></div></div></Section> }
function App(){const [lang,setLang]=useState(getInitialLang); const t=data[lang]; useEffect(()=>{document.documentElement.lang=lang},[lang]); return <><Nav t={t} lang={lang} setLang={setLang}/><main><Hero t={t}/><div className="container"><Section id="profile" eyebrow={t.sections.profileEyebrow} title={t.sections.profileTitle}><div className="profile-grid"><div className="card"><Briefcase/><h3>{t.hero.role}</h3><p>{t.hero.location}</p></div><div className="card"><p className="big">{t.sections.profileText}</p></div></div></Section><Experience t={t}/><Education t={t}/><Skills t={t}/><Contact t={t} lang={lang}/></div></main><footer>© {new Date().getFullYear()} Marcel Wlotzka · Interactive multilingual CV</footer></>}

createRoot(document.getElementById('root')).render(<App/>);
